### ISSUE TITLE
Fuzzing Javac

### ISSUE THREAD

**Issue by Aidongo** [EngineeringSoftware/jattack#1]
Have you ever used other fuzzer such as AFL or LibFuzzer to fuzz test Java compilers (e.g. Javac)? I don't seem to have found anything like this yet, but I think the project in this repository is a new idea.

**Comment by CptGit** [comment]
Thanks for your interest @Aidongo! I agree that JAttack can be used to test javac, too. JAttack can also be used to test any other software that takes programs as input, such as refactoring engines, with necessary adaption.

Also, there should be some existing work on testing javac. I know a recent paper  from PLDI 2022: "Finding typing compiler bugs".
https://dl.acm.org/doi/10.1145/3519939.3523427
https://github.com/hephaestus-compiler-project/hephaestus

Hope it helps!

**Comment by Aidongo** [comment]
The project I am currently working on involves exploring AFL's application for conducting fuzz testing on Java compilers. The article you shared has been particularly enlightening and has provided valuable insights for my research. I am grateful for your help!!!
